# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      # Ruff - 只检查，不修改
      - id: ruff-format-check
        name: ruff format check
        entry: bash -c 'PATH="$HOME/.local/bin:$PATH" uv run ruff format --check "$@"' --
        language: system
        types: [python]
        pass_filenames: true
        require_serial: true
      
      - id: ruff-check
        name: ruff check
        entry: bash -c 'PATH="$HOME/.local/bin:$PATH" uv run ruff check "$@"' --
        language: system
        types: [python]
        pass_filenames: true
        require_serial: true

      # Pyright - 类型检查
      - id: pyright
        name: pyright type check
        entry: bash -c 'PATH="$HOME/.local/bin:$PATH" uv run pyright'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      # Pytest - 测试（仅在 push 时）
      - id: pytest
        name: pytest
        entry: bash -c 'PATH="$HOME/.local/bin:$PATH" uv run pytest tests/ -v'
        language: system
        pass_filenames: false
        always_run: true