[project]
name = "bump-version"
version = "0.1.0"
description = "A CLI tool for semantic version management"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "ISC"}
authors = [
    {name = "AI App Base"},
]
dependencies = [
    "click>=8.1.0",
    "rich>=13.0.0",
    "inquirer>=3.1.0",
    "toml>=0.10.2",
    "packaging>=23.0",
]

[project.scripts]
bump-version-py = "bump_version.cli:main"
bvp = "bump_version.cli:main"

[project.urls]
Homepage = "https://github.com/ai-app-base/bump-version-py"
Repository = "https://github.com/ai-app-base/bump-version-py.git"
Issues = "https://github.com/ai-app-base/bump-version-py/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "bump_version/**/*.py",
    "bump_version/py.typed",
]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
]